### ISSUE TITLE
Bug in rdrand implementation...

### ISSUE THREAD

**Issue by dazoe** [puzzlehawk/dcrypt#1]
rdrand  R8; // Loads R8 with random bits...
mov R8, RAX; // Moves RAX to R8 clearing the random bits!!! (R8 ended up being 0x02 in my tests)
mov     [RDI], R8; // Stores R8 in the buffer
add     RDI, 8; // Advances pointer.

Not sure why the first move statement is in there... seem odd... Even has different formatting.

**Comment by dazoe** [comment]
Another thing to report, for some reason when using the lib I'm seeing a lot of access violations at the mov [RDI], R8 instruction.

**Comment by puzzlehawk** [comment]
Thanks for reporting. This looks strange indeed. I pushed a fix onto master branch together with several API changes which might be part of a next version.
Do you feel like doing some further testing? This would be a great help as I currently do not have access to a computer with RDRAND support.
